- name: Install extra packages needed by PHP
  apt:
    name: "{{ item }}"
  with_items:
  - libpng-dev
  - jpegoptim
  - optipng
  - pngquant
  - gifsicle

- name: Remove default VirtualHost config
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /etc/apache2/sites-available/000-default.conf
  - /etc/apache2/sites-available/default-ssl.conf

- name: Do not listen on HTTPS port
  replace:
    path: /etc/apache2/ports.conf
    regexp: "Listen 443"
    replace: ""

- name: Copy Apache2 config
  copy:
    src: "{{ inventory_dir }}/../docker/webserver/000-default.conf"
    dest: /etc/apache2/sites-available/000-default.conf
    mode: 0644

- name: Change webapp install path
  replace:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '\/var\/www\/public'
    replace: '/var/www/improv-ee/src/public'

- name: Enable default VirtualHost
  command: a2ensite 000-default
  notify: restart apache

- name: Remove default Apache2 html directory
  file:
    path: /var/www/html
    state: absent

- name: Enable Apache2 shell
  user:
    name: www-data
    shell: /bin/bash