- name: Remove default conf files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default

- name: Create folder for certificates
  file:
    path: /etc/ssl/certs/lb
    state: directory

- name: Check if dhparam file exists
  stat:
    path: /etc/ssl/certs/lb/dhparam.pem
  register: dhparam_file

- name: Generate dhparam
  command: openssl dhparam -out /etc/ssl/certs/lb/dhparam.pem 2048
  when: not dhparam_file.stat.exists

- name: Insert webapp IP to hosts file
  lineinfile:
    path: "{{ item }}"
    line: '127.0.0.1 webserver'
  with_items:
    - /etc/cloud/templates/hosts.debian.tmpl
    - /etc/hosts

- name: Copy load-balancer certificates
  copy:
    src: "{{ item }}"
    dest: "/etc/ssl/certs/lb/"
    owner: root
    group: root
    mode: 0660
  with_items:
  - web.crt
  - web.key

- name: Copy Cloudflare IP list
  copy:
    src: allow-ip.conf
    dest: /etc/nginx/

- name: Copy Nginx config
  copy:
    src: "{{ inventory_dir }}/../docker/lb/default.conf"
    dest: /etc/nginx/sites-enabled/
  notify: restart nginx

