
- name: Download latest version of source code
  git:
    repo: 'https://github.com/improv-ee/improv-ee.git'
    dest: /var/www/improv-ee
    version: master
    force: yes

- name: Make sure app data storage directories exists
  file:
    path: "{{ app_storage_dir }}/{{ item }}"
    state: directory
    owner: www-data
    group: root
    mode: 0770
  with_items:
  - app/public
  - framework/cache
  - framework/sessions
  - framework/testing
  - framework/views
  - logs

- name: Remove app default storage directory
  file:
    path: "{{ app_root_dir }}/storage"
    state: absent

- name: Link system storage directory
  file:
    src: "{{ app_storage_dir }}"
    dest: "{{ app_root_dir }}/storage"
    state: link

- name: Own the app by www-data
  file:
    path: /var/www/improv-ee
    owner: www-data
    group: www-data
    recurse: yes

- name: Copy environment file
  template:
    src: .env
    dest: "{{ app_root_dir }}/.env"
    owner: www-data
    group: root
    mode: 0650

- name: Copy update script
  copy:
    src: update.sh
    dest: /usr/local/bin/update-improv
    mode: 0760
    owner: www-data
    group: root

- name: Update and migrate the deployment
  shell: "update-improv | logger -t improv-update"
  become_user: www-data
  become: yes

- name: Set update script to run daily
  cron:
    name: Update improv-ee deployment
    hour: 02
    minute: 05
    job: "update-improv | logger -t improv-cron"
    user: www-data

- name: Set database reset script to run daily
  cron:
    name: Reset improv-ee database
    hour: 06
    minute: 05
    job: "cd {{ app_root_dir }} && /usr/bin/php artisan migrate:fresh --force && /usr/bin/php artisan db:seed --force"
    user: www-data


- name: Link public storage directory
  file:
    src: "{{ app_storage_dir }}/app/public"
    dest: "{{ app_root_dir }}/public/storage"
    state: link

- name: Generate Passport OAuth keys
  command: php artisan passport:keys
    args:
      chdir: "{{ app_root_dir }}"

- name: Install Passport
  command: php artisan passport:install
    args:
      chdir: "{{ app_root_dir }}"