- name: Configure Apache
  include: conf-apache.yml

- name: Configure Nginx
  include: conf-nginx.yml

- name: Install PHP app
  include: install-app.yml

- name: Install queue worker
  include: install-worker.yml
