language: php

php:
  - 7.2

before_script:
  - cp src/.env.testing src/.env

before_install:
  - sudo apt-get install -y libpng-dev jpegoptim optipng pngquant gifsicle

install:
  - composer install -d src --prefer-source --no-interaction --dev

script:
  - php src/artisan migrate
  - php src/vendor/bin/phpunit -c src/
  - php src/artisan api:generate --routePrefix="api/*" --output=src/public/docs

