language: php
sudo: required
services:
  - docker

php:
  - 7.2

before_script:
  - touch src/.env

before_install:
  - sudo apt-get install -y libpng-dev jpegoptim optipng pngquant gifsicle

install:
  - composer install -d src --no-interaction --dev
  - cd src && npm install && cd ..

script:
  - php src/vendor/bin/parallel-lint --exclude src/vendor src
  - php src/vendor/bin/phpunit -c src/
  - php src/artisan apidoc:generate
  - cd src && npm run prod && cd ..
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr / - ; fi`
  - docker build -t improv/improv-ee:$TAG .

after_success:
  - docker push improv/improv-ee:$TAG
  - docker rmi improv/improv-ee:$TAG

after_script:
  - docker logout
