language: php
sudo: required
services:
  - docker

php:
  - 7.2

before_script:
  - cp src/.env.testing src/.env

before_install:
  - sudo apt-get install -y libpng-dev jpegoptim optipng pngquant gifsicle

install:
  - composer install -d src --prefer-source --no-interaction --dev

script:
  - php src/artisan migrate
  - php src/vendor/bin/phpunit -c src/
  - php src/artisan apidoc:generate
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr / - ; fi`
  - docker build -t improv/improv-ee:$TAG .

after_success:
  - docker push improv/improv-ee:$TAG
  - docker rmi improv/improv-ee:$TAG

after_script:
  - docker logout
