language: php
sudo: required
services:
  - docker

cache:
  directories:
  - src/node_modules
  - src/vendor

php:
  - 7.2

jobs:
  include:
  - stage: "Test"
    name: "Run static analysis tools on code"
    script: .travis/static-analysis.sh
  - stage: "🐳Create build artifacts"
    script: .travis/build-webserver.sh
    name: "🐳Build Docker webserver image"
  - name: "📜Create API doc"
    script: .travis/make-apidoc.sh


before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: .travis/unittest.sh

after_script:
  - ./cc-test-reporter format-coverage --input-type=clover --prefix src/ tests/coverage.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT