language: php
sudo: required
services:
  - docker

cache:
  directories:
  - src/node_modules
  - src/vendor

php:
  - 7.2
  - 7.3

jobs:
  include:
  - stage: "Test"
    name: "Run static analysis tools on code"
    script: .travis/static-analysis.sh
  - stage: "🐳Create build artifacts"
    script: .travis/build-webserver.sh
    name: "🐳Build Docker webserver image"
  - name: "📜Create API doc"
    script: .travis/make-apidoc.sh

script: .travis/unittest.sh