language: php
sudo: required
services:
  - docker

cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.composer"
php:
  - 7.4

node_js: 8.9

jobs:
  include:
  - stage: "🤖 Run quality checks"
    name: "🕵️ Run static analysis tools on frontend JS/Vue code"
    script: .travis/static-js.sh
  - name: "🕵️ Run static analysis tools on backend PHP code"
    script: .travis/static-php.sh
  - name: "✔️ Run unit tests"
    script: .travis/unittest.sh
  - stage: "🐳 Create build artifacts"
    script: .travis/build-webserver.sh
    name: "🐳 Build Docker webserver image"
  - name: "📜 Create API doc"
    script: .travis/make-apidoc.sh
