version: "3.7"

services:
  webserver:
    build:
      context: .
      target: dev
    ports:
      - "8080"
    deploy:
      replicas: 2
    networks:
      backend:
      db:
      mail:
    environment:
      - APP_ENV=local
      - APP_URL=web.local.improvision.eu
    volumes:
      - ./src:/var/www/
    depends_on:
      - app-db
      - redis
      - import-db

  worker:
    build:
      context: .
    networks:
      - backend
      - db
      - mail
    environment:
      - APP_ENV=local
      - APP_URL=web.local.improvision.eu
    volumes:
      - ./src:/var/www/
    depends_on:
      - app-db
      - redis
    command: "php /var/www/artisan queue:work --tries=3"

  lb:
    build:
      context: docker/lb
    image: sqroot/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      backend:
        aliases:
          - web.local.improvision.eu
          - api.local.improvision.eu
    volumes:
      - ./docker/lb/certs:/etc/ssl/certs/lb:ro
    depends_on:
      - webserver


  app-db:
    image: mariadb:10
    environment:
    - MYSQL_ROOT_PASSWORD=5jzdDHBWV966YWXhGz1HMn7OTu0c0eJV
    - MYSQL_USER=improv_ee
    - MYSQL_PASSWORD=FHoXB8ONj4bvTTn7FXaix
    - MYSQL_DATABASE=improv_ee
    networks:
    - db
    ports:
    - 3308:3306
    volumes:
    - app-db:/var/lib/mysql

  apidoc:
    build:
      context: src/public/docs
    ports:
      - 8081:8080

  redis:
    image: redis:4-alpine
    networks:
      - db
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: --appendonly yes --requirepass C3azPJ6wk8wueiuDjM

  import-db:
    image: mariadb:10
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=improv_ee
      - MYSQL_PASSWORD=FHoXB8ONj4bvTTn7FXaix
      - MYSQL_DATABASE=improv_ee
    networks:
      - db
    ports:
      - 3307:3306
    volumes:
      - ./docker/import-db/export:/docker-entrypoint-initdb.d
      - import-db:/var/lib/mysql

  mailserver:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - mail

volumes:
  import-db:
  app-db:
  redis:

networks:
  backend:
  db:
  mail:
