- name: Update packages
  apt:
    name: "*"
    state: latest
    force_apt_get: true
    cache_valid_time: 600

- name: Install basic tooling
  apt:
    name: "{{ item }}"
  with_items:
    - screen
    - nano
