- name: Run basic setup
  import_playbook: setup.yml

- name: Install Redis
  import_playbook: redis.yml

- name: Install MariaDB
  import_playbook: mysql.yml

- name: Install webserver
  import_playbook: webserver.yml
